import { useState, createContext } from "react";

const videosContext = createContext();

export function VideosDataProvider({ children }) {
	const [mostPopularVids] = useState([
		{
			id: 5525,
			thumbnailSrc: "../../images/thumbnail1.jpg",
			title: "I Gave My 100,000,000th Subscriber An Island",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "65M views",
			date: "1 mounth ago",
			isVerified: true,
		},
		{
			id: 557845825,
			thumbnailSrc: "../../images/thumbnail2.jpg",
			title: "Could You Survive On Mars?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "3.9M views",
			date: "2 years ago",
			isVerified: true,
		},
		{
			id: 86858,
			thumbnailSrc: "../../images/thumbnail3.jpg",
			title: "I Survived Using Only Realistic Minecraft Tools",
			logoSrc: "../../images/logoRyan.jpg",
			channelName: "Ryan Trahan",
			views: "5.4M views",
			date: "1 year ago",
			isVerified: true,
		},
		{
			id: 55788725,
			thumbnailSrc: "../../images/thumbnail4.jpg",
			title: "$456,000 Squid Game In Real Life!",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "286M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 55786825,
			thumbnailSrc: "../../images/thumbnail5.jpg",
			title: "What Happens If You Hire 100 Bodyguards?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "5M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 5525,
			thumbnailSrc: "../../images/thumbnail1.jpg",
			title: "I Gave My 100,000,000th Subscriber An Island",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "65M views",
			date: "1 mounth ago",
			isVerified: true,
		},
		{
			id: 557845825,
			thumbnailSrc: "../../images/thumbnail2.jpg",
			title: "Could You Survive On Mars?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "3.9M views",
			date: "2 years ago",
			isVerified: true,
		},
		{
			id: 86858,
			thumbnailSrc: "../../images/thumbnail3.jpg",
			title: "I Survived Using Only Realistic Minecraft Tools",
			logoSrc: "../../images/logoRyan.jpg",
			channelName: "Ryan Trahan",
			views: "5.4M views",
			date: "1 year ago",
			isVerified: true,
		},
		{
			id: 55788725,
			thumbnailSrc: "../../images/thumbnail4.jpg",
			title: "$456,000 Squid Game In Real Life!",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "286M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 55786825,
			thumbnailSrc: "../../images/thumbnail5.jpg",
			title: "What Happens If You Hire 100 Bodyguards?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "5M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 5525,
			thumbnailSrc: "../../images/thumbnail1.jpg",
			title: "I Gave My 100,000,000th Subscriber An Island",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "65M views",
			date: "1 mounth ago",
			isVerified: true,
		},
		{
			id: 557845825,
			thumbnailSrc: "../../images/thumbnail2.jpg",
			title: "Could You Survive On Mars?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "3.9M views",
			date: "2 years ago",
			isVerified: true,
		},
		{
			id: 86858,
			thumbnailSrc: "../../images/thumbnail3.jpg",
			title: "I Survived Using Only Realistic Minecraft Tools",
			logoSrc: "../../images/logoRyan.jpg",
			channelName: "Ryan Trahan",
			views: "5.4M views",
			date: "1 year ago",
			isVerified: true,
		},
		{
			id: 55788725,
			thumbnailSrc: "../../images/thumbnail4.jpg",
			title: "$456,000 Squid Game In Real Life!",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "286M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 55786825,
			thumbnailSrc: "../../images/thumbnail5.jpg",
			title: "What Happens If You Hire 100 Bodyguards?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "5M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 5525,
			thumbnailSrc: "../../images/thumbnail1.jpg",
			title: "I Gave My 100,000,000th Subscriber An Island",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "65M views",
			date: "1 mounth ago",
			isVerified: true,
		},
		{
			id: 557845825,
			thumbnailSrc: "../../images/thumbnail2.jpg",
			title: "Could You Survive On Mars?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "3.9M views",
			date: "2 years ago",
			isVerified: true,
		},
		{
			id: 86858,
			thumbnailSrc: "../../images/thumbnail3.jpg",
			title: "I Survived Using Only Realistic Minecraft Tools",
			logoSrc: "../../images/logoRyan.jpg",
			channelName: "Ryan Trahan",
			views: "5.4M views",
			date: "1 year ago",
			isVerified: true,
		},
		{
			id: 55788725,
			thumbnailSrc: "../../images/thumbnail4.jpg",
			title: "$456,000 Squid Game In Real Life!",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "286M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 55786825,
			thumbnailSrc: "../../images/thumbnail5.jpg",
			title: "What Happens If You Hire 100 Bodyguards?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "5M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 5525,
			thumbnailSrc: "../../images/thumbnail1.jpg",
			title: "I Gave My 100,000,000th Subscriber An Island",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "65M views",
			date: "1 mounth ago",
			isVerified: true,
		},
		{
			id: 557845825,
			thumbnailSrc: "../../images/thumbnail2.jpg",
			title: "Could You Survive On Mars?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "3.9M views",
			date: "2 years ago",
			isVerified: true,
		},
		{
			id: 86858,
			thumbnailSrc: "../../images/thumbnail3.jpg",
			title: "I Survived Using Only Realistic Minecraft Tools",
			logoSrc: "../../images/logoRyan.jpg",
			channelName: "Ryan Trahan",
			views: "5.4M views",
			date: "1 year ago",
			isVerified: true,
		},
		{
			id: 55788725,
			thumbnailSrc: "../../images/thumbnail4.jpg",
			title: "$456,000 Squid Game In Real Life!",
			logoSrc: "../../images/logoMrBeast.jpg",
			channelName: "MrBeast",
			views: "286M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 55786825,
			thumbnailSrc: "../../images/thumbnail5.jpg",
			title: "What Happens If You Hire 100 Bodyguards?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "5M views",
			date: "1 years ago",
			isVerified: true,
		},
		{
			id: 557845825,
			thumbnailSrc: "../../images/thumbnail2.jpg",
			title: "Could You Survive On Mars?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "3.9M views",
			date: "2 years ago",
			isVerified: true,
		},
		{
			id: 86858,
			thumbnailSrc: "../../images/thumbnail3.jpg",
			title: "I Survived Using Only Realistic Minecraft Tools",
			logoSrc: "../../images/logoRyan.jpg",
			channelName: "Ryan Trahan",
			views: "5.4M views",
			date: "1 year ago",
			isVerified: true,
		},

		{
			id: 55786825,
			thumbnailSrc: "../../images/thumbnail5.jpg",
			title: "What Happens If You Hire 100 Bodyguards?",
			logoSrc: "../../images/logoAirrack.jpg",
			channelName: "Airrack",
			views: "5M views",
			date: "1 years ago",
			isVerified: true,
		},
	]);

	return <videosContext.Provider value={{ mostPopularVids }}>{children}</videosContext.Provider>;
}

export default videosContext;
